# Cubix block1 homework
# Miskovits Dániel

# 1. build the application with Maven
# 2. create and publish a Docker image
# 3. verify the resulting Docker image

name: Cubix block1 homework

on:
  push:
    branches:
    - main

jobs:
  maven-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        cache: 'maven'
    - name: Build with Maven
      run: ./mvnw package
       
  docker-publish:
    runs-on: ubuntu-latest
    needs: maven-build
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Logging in to Docker
      run: docker login ghcr.io -u miskovitsd -p ${{ github.token }}
    - name: Build the Docker image
      run: docker build . -t ghcr.io/miskovitsd/cubix/1/homework/app:springboot
    - name: Publishing the Docker image
      run: docker push ghcr.io/miskovitsd/cubix/1/homework/app:springboot

  docker-verify:
    runs-on: ubuntu-latest
    needs: docker-publish
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Verify image with a script
      run: |
         chmod +x ./verify-image.sh
         ./verify-image.sh
      shell: bash
      
    
